version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"  # Expose Streamlit frontend
    volumes:
      - ..:/crashpbo  # Mount the entire project directory
    working_dir: /crashpbo # Set the working directory inside the container

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ..:/crashpbo  # Mount the entire project directory
    working_dir: /crashpbo  # Set the working directory inside the container
    command: ["python", "-m", "crashpbo.interface.pbo_back_end", "quanser_pendulum"]
    restart: always  # Ensure the backend restarts automatically

  quanser:
    build:
      context: ..
      dockerfile: docker/Dockerfile.quanser
    volumes:
      - ..:/crashpbo  # Mount the entire project directory
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
      - SDL_VIDEODRIVER=x11
    working_dir: /crashpbo  # Set the working directory inside the container
    restart: always  # Ensure the backend restarts automatically
    command: python3 /quanser/PBO_experiment.py # sleep infinity  # Keep the container running indefinitely
    privileged: true  # Required to access the pendulum