# Use Python 3.9 as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /crashpbo

# Install Streamlit and other dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Streamlit default port
EXPOSE 8501

# Command to run the Streamlit app
CMD ["python", "-m", "streamlit", "run", "crashpbo/interface/pbo_front_end.py", "--server.enableCORS=false", "--server.port=8501", "--server.address=0.0.0.0"]
